<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFrameworks>net10.0-android</TargetFrameworks>
		<TargetFrameworks Condition="!$([MSBuild]::IsOSPlatform('linux'))">$(TargetFrameworks);net10.0-ios;net10.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>

		<OutputType>Library</OutputType>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);CS1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Core\ThemeForge.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<MauiXaml Update="Styles\ThemeForgeDefaults.xaml" Generator="MSBuild:Compile" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="Microsoft.AspNetCore.Components.WebView.Maui" Version="10.0.110" />
	</ItemGroup>
</Project>
